// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb3M2YXALA1lp6d2hTcw7_lg9TTNxXZYM',
    appId: '1:27398075562:web:3be24e0f27304042418cd3',
    messagingSenderId: '27398075562',
    projectId: 'chat-app-90078',
    authDomain: 'chat-app-90078.firebaseapp.com',
    databaseURL: 'https://chat-app-90078-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-app-90078.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAucjPzq4KtzdSPKIWDaYx_SGUuHpYxwv0',
    appId: '1:27398075562:android:8fe74a3ca7401738418cd3',
    messagingSenderId: '27398075562',
    projectId: 'chat-app-90078',
    databaseURL: 'https://chat-app-90078-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-app-90078.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD838vYD-KzX1GUK0I38_KqaILaXG4B_5o',
    appId: '1:27398075562:ios:c14c2908cba72b73418cd3',
    messagingSenderId: '27398075562',
    projectId: 'chat-app-90078',
    databaseURL: 'https://chat-app-90078-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-app-90078.appspot.com',
    iosBundleId: 'com.example.chatAppl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD838vYD-KzX1GUK0I38_KqaILaXG4B_5o',
    appId: '1:27398075562:ios:c14c2908cba72b73418cd3',
    messagingSenderId: '27398075562',
    projectId: 'chat-app-90078',
    databaseURL: 'https://chat-app-90078-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-app-90078.appspot.com',
    iosBundleId: 'com.example.chatAppl',
  );
}
